import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import { useRouter } from 'next/router'
import Link from "next/link";



const Home: NextPage = () => {
    const router = useRouter()
    const { id } = router.query
    const parsedId = parseInt(id as string)
    const {mutateAsync: mutate} = trpc.useMutation('participations.addOne');
    const {data: p, isLoading, refetch: refetchAll} =  trpc.useQuery(["participations.getAll"]);
    const {data: totalDistance, refetch: refetchDistance} =  trpc.useQuery(["participations.totalDistance"]);
    const {data: goalDistance} =  trpc.useQuery(["goal.totalDistance"]);
    const {data:profile} = trpc.useQuery(["participants.getOne", parsedId]);
    const {data:profileDistance} = trpc.useQuery(["participants.totalDistance", parsedId]);

    const refresh = async () => {
        await refetchAll();
        await refetchDistance();

    }
    return (
        <>
            <Head>
                <title>Défi Bacon</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={"container mx-auto md:py-20 md:px-16 py-10 px-8"}>
                <div className={"md:text-8xl text-5xl mb-10 font-poppins uppercase font-bold"}>{profile?.name}</div>
                <div className={"md:text-6xl text-4xl font-poppins"}>Il a couru {profileDistance} KM pour la cause.</div>
                <div className={"border-b-2 border-dark my-10"}></div>
                <div className={"md:text-6xl text-4xl font-poppins"}>Tu aimerais <span className={"font-bold"}>contribuer</span> ?</div>
                <div className={"flex md:flex-row flex-col my-8 md:space-x-3 md:space-y-0 space-y-5"}>
                    <div className={"w-max h-max hover:shadow py-4 px-4 rounded-lg cursor-pointer md:text-2xl  bg-primary text-white uppercase font-bold font-rubik"}><a target={"__blank__"} href={"https://www.gofundme.com/f/gofundme-en-la-mmoire-de-mon-frre-maxime?qid=ebd1a3895ff5966bc933b363abac173c"}>Donner à la cause</a></div>
                    <div  className={"w-max h-max hover:shadow py-4 px-4 rounded-lg cursor-pointer md:text-2xl bg-dark text-white uppercase font-bold font-rubik"}><Link href={"/app"}>Contribuer à la course</Link></div>
                </div>
            </div>
        </>
    );
};

export default Home;
