import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Header from "../components/utils/header";

const Home: NextPage = () => {
  const { mutateAsync: mutate } = trpc.useMutation("participations.addOne");
  const {
    data: p,
    isLoading,
    refetch: refetchAll,
  } = trpc.useQuery(["participations.getAll"]);
  const { data: totalDistance, refetch: refetchDistance } = trpc.useQuery([
    "participations.totalDistance",
  ]);
  const { data: goalDistance } = trpc.useQuery(["goal.totalDistance"]);
  const { data: current } = trpc.useQuery(["goal.current"]);

  const refresh = async () => {
    await refetchAll();
    await refetchDistance();
  };

  return (
    <>
      <Head>
        <title>Défi Bacon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"container mx-auto overflow-hidden"}>
        <Header current={current} />
      </div>
    </>
  );
};

export default Home;
