import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Form from "../components/Form";
import Board from "../components/Board";


const Home: NextPage = () => {
  const {mutateAsync: mutate} = trpc.useMutation('participations.addOne');
  const {data: p, isLoading, refetch: refetchAll} =  trpc.useQuery(["participations.getAll"]);
  const {data: totalDistance, refetch: refetchDistance} =  trpc.useQuery(["participations.totalDistance"]);

  const refresh = async () => {
    await refetchAll();
    await refetchDistance();

  }
  return (
    <>
      <Head>
        <title>Défi Bacon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"container mx-auto"}>
        <Form refresh={refresh} mutate={mutate}/>
        <Board isLoading={isLoading} p={p} total={totalDistance}/>
      </div>
    </>
  );
};

export default Home;
